services:
    next-app:
        container_name: next-app
        build:
            context: ./next-app
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3000:3000
